name: Deployment
on: 
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version : 12
        
      - run : npm run --prefix .\e-commerce dev 
      - uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: master
          


